'use strict';
// Tiny actual-client scheduling regression only. Reads source metadata, evaluates the actual
// client and executor with synthetic tools/clock, and never executes helpers.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const ROOT=process.argv[2];assert(path.isAbsolute(ROOT));
const FRESH_CLIENT_PATH=process.argv[3];assert(path.isAbsolute(FRESH_CLIENT_PATH));
const CLIENT_PATH=path.join(ROOT,'scripts/radio_native_v2_tool_courier_client.js');
const FIXTURE_PATH=path.join(ROOT,'scripts/radio_native_v3_compact_eight_case_resource_fixture.py');
const hash=value=>crypto.createHash('sha256').update(value).digest('hex');
const clientRaw=fs.readFileSync(CLIENT_PATH),fixtureRaw=fs.readFileSync(FIXTURE_PATH);
const oldBlock=`    const settled=await Promise.allSettled(reads.map(p=>call('exec_command',p.arguments,p.response_reserved_bytes,'actual_source_read',deadline)));
    const parts=[],descriptors=[];
    for(let i=0;i<settled.length;i++){
      const result=settled[i];assert(result.status==='fulfilled','Source extraction failed; whole scope closed');
      const raw=result.value,p=reads[i];assert(raw.exit_code===0&&raw.session_id===undefined&&typeof raw.output==='string'&&`;
const newBlock=`    const parts=[],descriptors=[];
    for(let i=0;i<reads.length;i++){
      const p=reads[i],raw=await call('exec_command',p.arguments,p.response_reserved_bytes,'actual_source_read',deadline);
      assert(raw.exit_code===0&&raw.session_id===undefined&&typeof raw.output==='string'&&`;
function deriveClient(source){assert.equal(source.split(oldBlock).length,2,'One exact pinned read-dispatch block required');return source.replace(oldBlock,newBlock);}
const freshSource=fs.readFileSync(FRESH_CLIENT_PATH,'utf8');
assert.equal(freshSource,deriveClient(clientRaw.toString('utf8')),'Actual prospective derived client differs from independently specified exact transformation');
const serialMatch=fixtureRaw.toString('utf8').match(/SERIAL_EXECUTOR_HELPER = '''(.*?)'''/s);assert(serialMatch);
const serialSource=serialMatch[1];
function loadClient(source){const module={exports:{}};vm.runInNewContext(source,{module},{timeout:1000});return module.exports;}
const original=loadClient(clientRaw.toString('utf8')),fresh=loadClient(freshSource);
const serializeLocalExecutor=vm.runInNewContext(serialSource+'\nserializeLocalExecutor;',{}, {timeout:1000});
const h={sha256:hash,utf8Bytes:value=>Buffer.byteLength(value,'utf8'),sha256Chunks:chunks=>{const d=crypto.createHash('sha256');for(const x of chunks)d.update(x);return d.digest('hex');}};
class Clock {
  constructor(){this.now=0;this.next=0;this.events=new Map();this.fired=[];this.registered=[];this.cleared=[];}
  set(fn,delay,label='ack'){assert(Number.isFinite(delay)&&delay>=0);const id=++this.next;this.events.set(id,{id,at:this.now+delay,fn,label});this.registered.push({id,at:this.now,delay,label});return id;}
  clear(id){this.cleared.push({id,at:this.now});this.events.delete(id);}
  async flush(){for(let i=0;i<8;i++)await Promise.resolve();await new Promise(resolve=>setImmediate(resolve));}
  async step(){await this.flush();const next=[...this.events.values()].sort((a,b)=>a.at-b.at||a.id-b.id)[0];if(!next)return false;this.events.delete(next.id);this.now=next.at;this.fired.push({at:this.now,label:next.label});next.fn();await this.flush();return true;}
}
function sourcePlan(c,count=38){
  const params=JSON.stringify({repository_full_name:'andersenmartin-blip/setisearch',tree_elements:[{path:'synthetic-only',mode:'100644',type:'blob',content:'x'.repeat(1200)}]});
  const sourcePath='/synthetic/cases/case00/store/items/request-000001/part',sourceSha=hash(params),python='/synthetic/python';
  const quote=value=>"'"+value.replace(/'/g,"'\\''")+"'",program='import os,sys; f=os.open(sys.argv[1],os.O_RDONLY|os.O_NOFOLLOW); n=int(sys.argv[3]); b=os.pread(f,n,int(sys.argv[2])); assert len(b)==n; sys.stdout.buffer.write(b); os.close(f)';
  const width=Math.ceil(params.length/count),reads=[];let offset=0;
  for(let ordinal=0;ordinal<count;ordinal++){const bytes=ordinal===count-1?params.length-offset:width,output=params.slice(offset,offset+bytes);assert(bytes>0);reads.push({ordinal,tool:'exec_command',path:sourcePath,offset,bytes,source_sha256:sourceSha,output_sha256:hash(output),response_reserved_bytes:16384,arguments:{cmd:quote(python)+' -I -S -B -c '+quote(program)+' '+quote(sourcePath)+' '+offset+' '+bytes,max_output_tokens:400000,yield_time_ms:1000}});offset+=bytes;}
  assert.equal(offset,params.length);const request_prefix='{"tool":'+JSON.stringify('mcp__codex_apps__github_create_tree')+',"arguments":',request_suffix='}',request=request_prefix+params+request_suffix;
  return {python,params,reads,view:{schema:'radio-native-v2-existing-request-view-v1',offset:0,bytes:params.length,path:sourcePath,sha256:sourceSha,source_sha256:sourceSha,request_prefix,request_suffix,request_bytes:Buffer.byteLength(request),request_sha256:hash(request)}};
}
async function scenario(name,c,{delay=4000,deadline=550000,invalid=null,invalidOrdinal=0,rejectOrdinal=null}={}){
  const clock=new Clock(),plan=sourcePlan(c),byCmd=new Map(plan.reads.map(p=>[p.arguments.cmd,p])),physical=[],delivered=[],connectors=[],startup={cmd:'synthetic controller only',max_output_tokens:400000,yield_time_ms:30000};let deliveryOrdinal=0,active=0,maxActive=0;
  const argsFor=operation=>operation==='fetch'?{url:'https://api.github.com/repos/andersenmartin-blip/setisearch/git/ref/heads/m43-support-qualification'}:operation==='create_commit'?{repository_full_name:'andersenmartin-blip/setisearch',parent_sha:'a'.repeat(40),tree_sha:'b'.repeat(40),message:'synthetic only'}:{repository_full_name:'andersenmartin-blip/setisearch',branch_name:'m43-support-qualification',sha:'c'.repeat(40),force:false};
  const frame=ordinal=>({schema:c.CONTROLLER_SCHEMA,kind:'request',ordinal,tool:'mcp__codex_apps__github_'+c.CLIENT_SEQUENCE[ordinal],arguments:ordinal===1?null:argsFor(c.CLIENT_SEQUENCE[ordinal]),request_view:ordinal===1?plan.view:null,reads:ordinal===1?plan.reads:[],delivery_request_reserved_bytes:1024*1024,worker_deadline_epoch_ms:deadline,deadline_ms:deadline,automatic_retry:false});
  const output=ordinal=>({output:JSON.stringify(frame(ordinal))+'\n',session_id:741,synthetic_fixture:true});
  const execLocal=serializeLocalExecutor(args=>new Promise((resolve,reject)=>{const p=byCmd.get(args.cmd);assert(p);physical.push({ordinal:p.ordinal,at:clock.now});maxActive=Math.max(maxActive,++active);const d=typeof delay==='function'?delay(p.ordinal):delay;clock.set(()=>{active--;if(p.ordinal===rejectOrdinal)return reject(Error('synthetic physical helper refusal'));let raw={exit_code:0,output:plan.params.slice(p.offset,p.offset+p.bytes),synthetic_fixture:true};if(p.ordinal===invalidOrdinal&&invalid==='hash')raw.output='!'+raw.output.slice(1);if(p.ordinal===invalidOrdinal&&invalid==='length')raw.output+='!';if(p.ordinal===invalidOrdinal&&invalid==='exit')raw.exit_code=2;if(p.ordinal===invalidOrdinal&&invalid==='session')raw.session_id=99;if(p.ordinal===invalidOrdinal&&invalid==='metadata')raw.detail='z'.repeat(8200);resolve(raw);},d,'physical-'+p.ordinal);}));
  const tools={exec_command:args=>args.cmd===startup.cmd?Promise.resolve(output(0)):execLocal(args),write_stdin:async args=>{assert(args.chars&&args.session_id===741);const body=JSON.parse(args.chars);assert.equal(body.ordinal,deliveryOrdinal);delivered.push(body);deliveryOrdinal++;return deliveryOrdinal<6?output(deliveryOrdinal):{exit_code:0,output:JSON.stringify({schema:c.CONTROLLER_SCHEMA,kind:'terminal',status:'SINGLE_CASE_COMPONENT_ONLY',fixture_only:true})+'\n',synthetic_fixture:true};}};
  for(const tool of Object.keys(c.CLIENT_CORE))tools[tool]=async args=>{connectors.push({tool,args,at:clock.now});return {isError:false,synthetic_fixture:true,output:'bounded synthetic connector envelope'};};
  let complete=false,atReturn=null,snapshot=null;
  const resultPromise=c.runToolCourier(tools,{hostLibrary:h,python:plan.python,startup_arguments:startup,max_actual_calls:59,max_request_bytes:40*1024*1024,max_response_bytes:64*1024*1024-256*1024,support_yield_time_ms:30000,clock:()=>clock.now,setTimer:(fn,ms)=>clock.set(fn,ms),clearTimer:id=>clock.clear(id)}).then(result=>{complete=true;atReturn=clock.now;snapshot=JSON.parse(JSON.stringify(result));return result;});
  for(let steps=0;!complete&&steps<1000;steps++){if(!await clock.step()){await clock.flush();assert(complete,'Synthetic event graph stalled');}}
  assert(complete);await resultPromise;const physicalAtReturn=physical.length;
  for(let steps=0;steps<1000&&await clock.step();steps++);assert.equal(clock.events.size,0);
  const rows=snapshot.records.filter(r=>r.kind==='actual_source_read');
  assert.equal(active,0);assert.equal(maxActive,1);assert.equal(clock.registered.filter(x=>x.label==='ack').length,snapshot.usage.calls);assert.equal(clock.cleared.length,snapshot.usage.calls);
  return {name,status:snapshot.status,reason:snapshot.reason,at_return_ms:atReturn,physical_at_return:physicalAtReturn,physical_total_after_draining:physical.length,maximum_active_physical_reads:maxActive,physical_dispatches:physical,ack_timer_registrations:clock.registered.filter(x=>x.label==='ack').length,ack_timer_clears:clock.cleared.length,ack_timer_fires:clock.fired.filter(x=>x.label==='ack').length,recorded_source_calls:rows.length,recorded_source_call_times:rows.map(r=>r.dispatch_at_epoch_ms),source_responses_unknown_at_return:rows.filter(r=>r.response_unknown).length,usage:snapshot.usage,automatic_retry:snapshot.automatic_retry,connector_requests:snapshot.connector_requests,delivered_source_descriptors:delivered.find(x=>x.ordinal===1)?.read_descriptors||[],snapshot,plan};
}
async function main(){
  const rows=[];
  const old=await scenario('old eager client plus actual v3 serial executor',original);rows.push(old);assert.equal(old.status,'CLOSED_FAILED');assert.equal(old.at_return_ms,120000);assert.equal(old.recorded_source_calls,38);assert.equal(old.physical_total_after_draining,38);assert(old.physical_total_after_draining>old.physical_at_return,'Old queue must demonstrate post-client-closure dispatch');
  const pass=await scenario('fresh sequential client plus actual v3 serial executor',fresh);rows.push(pass);assert.equal(pass.status,'SINGLE_CASE_COMPONENT_COMPLETE');assert.equal(pass.at_return_ms,152000);assert.equal(pass.recorded_source_calls,38);assert.equal(pass.usage.calls,51);assert.equal(pass.connector_requests,6);assert.equal(pass.delivered_source_descriptors.length,38);assert.equal(pass.usage.unknown_response_count,0);assert.deepEqual(pass.physical_dispatches.map(r=>r.ordinal),Array.from({length:38},(_,i)=>i));assert.deepEqual(pass.recorded_source_call_times,pass.physical_dispatches.map(r=>r.at));
  for(let i=0;i<38;i++){const p=pass.plan.reads[i],r=pass.snapshot.records.filter(r=>r.kind==='actual_source_read')[i],d=pass.delivered_source_descriptors[i];assert.equal(r.request_json,JSON.stringify({tool:'exec_command',arguments:p.arguments}));assert.equal(r.response_sha256,hash(r.response_json));assert.equal(r.response_bytes,Buffer.byteLength(r.response_json));assert.equal(d.offset,p.offset);assert.equal(d.bytes,p.bytes);assert.equal(d.source_sha256,p.source_sha256);assert.equal(d.envelope_sha256,r.response_sha256);assert.equal(d.envelope_bytes,r.response_bytes);}
  for(const invalid of ['hash','length','exit','session','metadata']){const r=await scenario('fresh invalid first read '+invalid,fresh,{invalid});rows.push(r);assert.equal(r.status,'CLOSED_FAILED');assert.equal(r.recorded_source_calls,1);assert.equal(r.physical_total_after_draining,1);assert.equal(r.connector_requests,1);if(invalid==='metadata')assert.match(r.reason,/Bounded complete observed read envelope metadata required/);}
  const laterInvalid=await scenario('fresh invalid seventh read stops remaining dispatch',fresh,{invalid:'hash',invalidOrdinal:7});rows.push(laterInvalid);assert.equal(laterInvalid.status,'CLOSED_FAILED');assert.equal(laterInvalid.recorded_source_calls,8);assert.equal(laterInvalid.physical_total_after_draining,8);assert.equal(laterInvalid.connector_requests,1);
  const rejected=await scenario('fresh first physical helper rejection',fresh,{rejectOrdinal:0});rows.push(rejected);assert.equal(rejected.status,'CLOSED_FAILED');assert.equal(rejected.recorded_source_calls,1);assert.equal(rejected.physical_total_after_draining,1);assert.equal(rejected.source_responses_unknown_at_return,1);
  const ack=await scenario('fresh actual 120-second read acknowledgement expiry',fresh,{delay:130000});rows.push(ack);assert.equal(ack.status,'CLOSED_FAILED');assert.equal(ack.at_return_ms,120000);assert.match(ack.reason,/acknowledgement deadline lost/);assert.equal(ack.recorded_source_calls,1);assert.equal(ack.physical_total_after_draining,1);assert.equal(ack.source_responses_unknown_at_return,1);
  const worker=await scenario('fresh absolute worker deadline expiry',fresh,{deadline:12000});rows.push(worker);assert.equal(worker.status,'CLOSED_FAILED');assert.equal(worker.at_return_ms,12000);assert.equal(worker.recorded_source_calls,3);assert.equal(worker.physical_total_after_draining,3);
  const whole=await scenario('fresh unchanged 600-second case deadline expiry',fresh,{delay:20000,deadline:900000});rows.push(whole);assert.equal(whole.status,'CLOSED_FAILED');assert.equal(whole.at_return_ms,600000);assert.equal(whole.recorded_source_calls,30);assert.equal(whole.physical_total_after_draining,30);
  for(const r of rows){assert.equal(r.automatic_retry,false);assert.equal(r.snapshot.execution_authorized,false);assert.equal(r.snapshot.scientific_execution_authorized,false);assert.equal(r.snapshot.rng_draws,0);assert.equal(r.snapshot.telescope_reads,0);assert.equal(r.usage.calls,r.snapshot.records.length);assert.equal(r.usage.request_bytes,r.snapshot.records.reduce((n,x)=>n+x.request_bytes,0));assert.equal(r.usage.response_charged_bytes,r.snapshot.records.reduce((n,x)=>n+x.response_charged_bytes,0));}
  assert(fs.readFileSync(CLIENT_PATH).equals(clientRaw));assert(fs.readFileSync(FIXTURE_PATH).equals(fixtureRaw));
  const result={schema:'radio-native-v3-prospective-derived-client-scheduler-regression-v1',status:'PASSED',scenario_count:rows.length,actual_client_source:{path:CLIENT_PATH,bytes:clientRaw.length,sha256:hash(clientRaw)},actual_serial_executor_source:{fixture_path:FIXTURE_PATH,fixture_bytes:fixtureRaw.length,fixture_sha256:hash(fixtureRaw),helper_bytes:Buffer.byteLength(serialSource),helper_sha256:hash(serialSource)},prospective_transformed_client:{bytes:Buffer.byteLength(freshSource),sha256:hash(freshSource)},old_exact_block:oldBlock,fresh_exact_block:newBlock,clock_model:'Deterministic accelerated synthetic clock; actual client timer callbacks and promises; one earliest event at a time with microtask quiescence.',cases:rows.map(({snapshot,plan,physical_dispatches,delivered_source_descriptors,recorded_source_call_times,...row})=>({...row,ordered_physical_ordinals:physical_dispatches.map(r=>r.ordinal),source_descriptor_count:delivered_source_descriptors.length,actual_record_and_physical_dispatch_times_equal:JSON.stringify(recorded_source_call_times)===JSON.stringify(physical_dispatches.slice(0,recorded_source_call_times.length).map(r=>r.at))})),implementation_source_files_modified:false,original_e_files_modified:false,private_ledger_files_read:false,actual_helpers_executed:0,actual_controls_executed:0,actual_connector_calls:0,network_fetches:0,scientific_cases:0,rng_draws:0,telescope_reads:0,automatic_retry:false,qualification_scope:'Prospective scheduler regression only; not actual F control qualification.'};
  process.stdout.write(JSON.stringify(result)+'\n');
}
main().catch(error=>{process.stderr.write(String(error.stack||error)+'\n');process.exitCode=1;});
