// Execute this function in Work Mode code mode with its tools object available.
// Handles only the declared synthetic reservation ledger, never telescope URLs.
async function radioReservationRpc(request) {
    const location = {
        kind: "github", repository: "andersenmartin-blip/setisearch",
        branch: "m43-support-qualification",
        path: "results_radio_acquisition_2026-09-26/published_fixture_ledger.json"
    };
    for (const key of Object.keys(location)) {
        if (request.location?.[key] !== location[key]) throw Error("RPC location changed");
    }
    if (!Number.isSafeInteger(request.sequence) || request.sequence < 1) throw Error("Invalid RPC sequence");
    if (!["read", "publish"].includes(request.rpc)) throw Error("Unknown RPC action");
    const branchResult = await tools.mcp__codex_apps__github_fetch({
        url: "https://api.github.com/repos/" + location.repository + "/branches/" + location.branch
    });
    if (branchResult.isError) throw Error("Cannot read publication branch");
    const branch = JSON.parse(branchResult.structuredContent.content);
    const revision = branch.commit.sha;
    const fileResult = await tools.mcp__codex_apps__github_fetch_file({
        repository_full_name: location.repository, path: location.path, ref: revision
    });
    if (fileResult.isError) throw Error("Missing reservation ledger; never initialize implicitly");
    const content = fileResult.structuredContent.content;
    if (request.rpc === "read") return {ok: true, sequence: request.sequence, revision, content};
    if (revision !== request.expected_revision) throw Error("Compare-and-swap revision conflict");
    const oldDocument = JSON.parse(content);
    const next = request.document;
    const shellQuote = value => "'" + value.replaceAll("'", "'\\''") + "'";
    const python = "import hashlib,json,sys;d=json.loads(sys.argv[1]);print(hashlib.sha256(json.dumps(d,sort_keys=True,separators=(',',':'),allow_nan=False).encode()).hexdigest())";
    const hashResult = await tools.exec_command({
        cmd: "python -c " + shellQuote(python) + " " + shellQuote(content), max_output_tokens: 100
    });
    if (hashResult.exit_code !== 0 || hashResult.output.trim() !== request.expected_ledger_sha256)
        throw Error("Compare-and-swap content conflict");
    if (!Array.isArray(next?.reservations) || next.reservations.length !== oldDocument.reservations.length + 1)
        throw Error("Exactly one new reservation required");
    const oldRoot = {...oldDocument, reservations: []};
    const nextRoot = {...next, reservations: []};
    // JSON source is generated by the same canonical Python encoder in the worker.
    const canonical = value => value && typeof value === "object"
        ? Array.isArray(value) ? value.map(canonical)
        : Object.fromEntries(Object.keys(value).sort().map(key => [key, canonical(value[key])])) : value;
    if (JSON.stringify(canonical(oldRoot)) !== JSON.stringify(canonical(nextRoot)) ||
        JSON.stringify(canonical(oldDocument.reservations)) !== JSON.stringify(canonical(next.reservations.slice(0, -1))))
        throw Error("Reservation publication is not append-only");
    if (next.reservations.at(-1).prior_ledger_sha256 !== request.expected_ledger_sha256)
        throw Error("Reservation parent changed");
    const tree = await tools.mcp__codex_apps__github_create_tree({
        repository_full_name: location.repository, base_tree_sha: branch.commit.commit.tree.sha,
        tree_elements: [{path: location.path, mode: "100644", type: "blob", content: JSON.stringify(canonical(next), null, 2) + "\n"}]
    });
    if (tree.isError) throw Error("Reservation tree creation failed");
    const commit = await tools.mcp__codex_apps__github_create_commit({
        repository_full_name: location.repository, parent_sha: revision, tree_sha: tree.structuredContent.sha,
        message: "Reserve complete quota before synthetic radio acquisition process " + next.reservations.at(-1).ordinal
    });
    if (commit.isError) throw Error("Reservation commit creation failed");
    const updated = await tools.mcp__codex_apps__github_update_ref({
        repository_full_name: location.repository, branch_name: location.branch,
        sha: commit.structuredContent.sha, force: false
    });
    if (updated.isError || updated.structuredContent?.success !== true) throw Error("Reservation ref update failed");
    return {ok: true, sequence: request.sequence, revision: commit.structuredContent.sha};
}
